# Generated by Django 5.1 on 2024-08-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneIDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ctzn', models.CharField(blank=True, max_length=255, null=True)),
                ('per_adr', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=9, null=True)),
                ('pport_issue_place', models.CharField(blank=True, max_length=255, null=True)),
                ('gd', models.IntegerField(blank=True, null=True)),
                ('natn', models.CharField(blank=True, max_length=255, null=True)),
                ('pport_issue_date', models.DateField(blank=True, null=True)),
                ('pport_expr_date', models.DateField(blank=True, null=True)),
                ('pport_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.CharField(blank=True, max_length=14, null=True)),
                ('mob_phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('mid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=1, null=True)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ret_cd', models.IntegerField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('identity_common', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token_expire_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
